SwitchSupport.Web/Areas/Admin/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSupport.Application.Services.Interfaces;
using SwitchSupport.Domain.Entities.Tags;
using SwitchSupport.Domain.ViewModels.Question;
using SwitchSupport.Web.ActionFilters;

namespace SwitchSupport.Web.Areas.Admin.Controllers
{
    [PermissionChecker(3)]
    public class QuestionController : AdminBaseController
    {
        #region ctor
        private readonly IQuestionService _questionService;
        public QuestionController(IQuestionService questionService)
        {
            _questionService = questionService;
        }
        #endregion
        public async Task<IActionResult> QuestionsList(FilterQuestionViewModel filter)
        {
            var result = await _questionService.GetAllQuestions(filter);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteQuestion(long questionId)
        {
            var result = await _questionService.DeleteQuestion(questionId);
            if (result == false)
            {
                return new JsonResult(new { status = "error", msg = "عملیات با موفقیت انجام نشد ." });

            }
            return new JsonResult(new { status = "success", msg = "عملیات با موفقیت انجام شد ." });
        }
        [HttpPost]
        public async Task<IActionResult> changeQuestionIsCheckedStatus(long questionId)
        {
            var result = await _questionService.changeQuestionIsCheckedStatus(questionId);
            if (result == false)
            {
                return new JsonResult(new { status = "error", msg = "عملیات با موفقیت انجام نشد ." });

            }
            return new JsonResult(new { status = "success", msg = "عملیات با موفقیت انجام شد ." });
        }
    }
}

SwitchSupport.Web/Areas/UserPanel/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSupport.Application.Extensions;
using SwitchSupport.Application.Services.Interfaces;
using SwitchSupport.Domain.ViewModels.UserPanel.Question;

namespace SwitchSupport.Web.Areas.UserPanel.Controllers
{
    public class QuestionController : UserPanelBaseController
    {
        private readonly IQuestionService _questionService;

        public QuestionController(IQuestionService questionService)
        {
            _questionService = questionService;
        }

        #region QuestionBookMarks

        [HttpGet]
        public async Task<IActionResult> QuestionBookMarks(FilterQuestionBookMarksViewModel filter)
        {
            filter.userId = User.GetUserId();
            filter.TakeEntitiy = 1;
            var result = await _questionService.GetQuestionBookMarks(filter);

            return View(result);
        }

        #endregion
    }
}

SwitchSupport.Web/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SwitchSupport.Application.Extensions;
using SwitchSupport.Application.Services.Interfaces;
using SwitchSupport.Domain.Enums;
using SwitchSupport.Domain.ViewModels.Question;

namespace SwitchSupport.Web.Controllers
{
    public class QuestionController : BaseController
    {
        private readonly IQuestionService _questionService;

        #region ctor
        public QuestionController(IQuestionService questionService)
        {
            _questionService = questionService;
        }
        #endregion

        #region Question
        [HttpGet("get-question")]
        public async Task<IActionResult> GetAllQuestion(string name)
        {
            var question = await _questionService.GetQuestion();
            var result = question.Where(q => q.Title.Contains(name.ToLower())).Select(q => q.Title).ToList();
            return Json(result);
        }


        [Authorize]
        [HttpGet("create-question")]
        public async Task<IActionResult> CreateQuestion()
        {
            return View();
        }


        [HttpPost("create-question"), ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateQuestion(CreateQuestionViewModel createQuestion)
        {           
                var tagvalidation = await _questionService.CheckTagValidation(HttpContext.User.GetUserId(), createQuestion.SelectTags);

            if (tagvalidation.Status == CreateQuestionEnum.NotValidTag)
            {
                createQuestion.SelectTagsJson = JsonConvert.SerializeObject(createQuestion.SelectTags);
                createQuestion.SelectTags = null;
                TempData[ErrorMessage] = tagvalidation.Message;
                return View(createQuestion);
            }
            if (!ModelState.IsValid)
            {
                createQuestion.SelectTagsJson = JsonConvert.SerializeObject(createQuestion.SelectTags);
                createQuestion.SelectTags = null;
                TempData[ErrorMessage] = "مشکلی در پارامتر های ورودی رخ داده است";
                return View(createQuestion);
            }    
            createQuestion.UserId = HttpContext.User.GetUserId();
            var result = await _questionService.AddQuestion(createQuestion);
            if (result)
            {
                TempData[SuccessMessage] = "عملیات با موفقیت انجام شد.";
                return Redirect("/");
            }

            createQuestion.SelectTagsJson = JsonConvert.SerializeObject(createQuestion.SelectTags);
            createQuestion.SelectTags = null;
            return View(createQuestion);
        }

        [HttpPost("ScoreUpForQuestion")]
		[ValidateAntiForgeryToken]

		public async Task<IActionResult> ScoreUpForQuestion(long questionId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return new JsonResult(new { status = "NotAuth" });
            }
            var result = await _questionService.CreateScoreForQuestion(questionId, QustionScore.Plus, User.GetUserId());

            switch (result)
            {
                case QuestionScoreResult.error:
                    return new JsonResult(new { status = "error" });
                    break;
                case QuestionScoreResult.MinScoreForUpScoreQuestion:
                    return new JsonResult(new { status = "MinScoreForUpScoreQuestion" });
                    break;
                case QuestionScoreResult.MinScoreForDownScoreQuestion:
                    return new JsonResult(new { status = "MinScoreForDownScoreQuestion" });
                    break;
                case QuestionScoreResult.IsExistsUserScoreForQuestion:
                    return new JsonResult(new { status = "IsExistsUserScoreForQuestion" });
                    break;
                case QuestionScoreResult.success:
                    return new JsonResult(new { status = "success" });
                    break;
                default:
                    return NotFound();
            }
        }

        [HttpPost("ScoreDownForQuestion")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> ScoreDownForQuestion(long questionId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return new JsonResult(new { status = "NotAuth" });
            }

            var result = await _questionService.CreateScoreForQuestion(questionId, QustionScore.Minus, User.GetUserId());

            switch (result)
            {
                case QuestionScoreResult.error:
                    return new JsonResult(new { status = "error" });
                    break;
                case QuestionScoreResult.MinScoreForUpScoreQuestion:
                    return new JsonResult(new { status = "MinScoreForUpScoreQuestion" });
                    break;
                case QuestionScoreResult.MinScoreForDownScoreQuestion:
                    return new JsonResult(new { status = "MinScoreForDownScoreQuestion" });
                    break;
                case QuestionScoreResult.IsExistsUserScoreForQuestion:
                    return new JsonResult(new { status = "IsExistsUserScoreForQuestion" });
                    break;
                case QuestionScoreResult.success:
                    return new JsonResult(new { status = "success" });
                    break;
                default:
                    return NotFound();
            }
        }

        [HttpGet("editquestion/{questionId}")]
        [Authorize]
        public async Task<IActionResult> EditQuestion(long questionId)
        {
            var res = await _questionService.FillEditQuestionViewModel(questionId,User.GetUserId());
            if (res == null) return NotFound();
            return View(res);
        }

        [HttpPost("editquestion/{questionId}"),ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> EditQuestion(EditQuestionViewModel editQuestion)
        {
            var tagvalidation = await _questionService.CheckTagValidation(HttpContext.User.GetUserId(), editQuestion.SelectedTags);

            if (tagvalidation.Status == CreateQuestionEnum.NotValidTag)
            {
                editQuestion.SelectTagsJson = JsonConvert.SerializeObject(editQuestion.SelectedTags);
                editQuestion.SelectedTags = null;
                TempData[ErrorMessage] = tagvalidation.Message;
                return View(editQuestion);
            }
            if (!ModelState.IsValid)
            {
                editQuestion.SelectTagsJson = JsonConvert.SerializeObject(editQuestion.SelectedTags);
                editQuestion.SelectedTags = null;
                TempData[ErrorMessage] = "مشکلی در پارامتر های ورودی رخ داده است";
                return View(editQuestion);
            }
            //TODO  Dar create ham moshkel darim dar vm
            var result = await _questionService.EditQuestion(editQuestion);
            if (result)
            {
                TempData[SuccessMessage] = "عملیات با موفقیت انجام شد.";
                return Redirect("/");
            }

            editQuestion.SelectTagsJson = JsonConvert.SerializeObject(editQuestion.SelectedTags);
            editQuestion.SelectedTags = null;
            return View(editQuestion);
        }

        #endregion

        #region Tags
        [HttpGet("get-tags")]
        public async Task<IActionResult> GetTags(string name)
        {
            var tags = await _questionService.GetAllTags();
            var qu = tags.Where(t => t.Title.Contains(name)).Select(t => t.Title).ToList();

            return Json(qu);
        }


        [Route("tags")]
        public async Task<IActionResult> FilterTag(FilterTagViewModel filter)
        {
            var result = await _questionService.GetAllFilterTags(filter);
            return View(result);
        }

        #endregion

        #region Question List
        [Route("question")]
        public async Task<IActionResult> QuestionList(FilterQuestionViewModel filter)
        {
            var result = await _questionService.GetAllQuestions(filter);
            return View(result);
        }


        [Route("question/{questionId}")]
        public async Task<IActionResult> GetQuestionDetails(long questionId)
        {
            var question = await _questionService.GetQuestionById(questionId);
            var userIp = Request.HttpContext.Connection.RemoteIpAddress;
            if (question == null) return NotFound();
            if (userIp != null)
            {
                await _questionService.AddViewForQuestion(userIp.ToString(), question);
            }
            ViewBag.bookmarks = false;

            if(User.Identity.IsAuthenticated && await _questionService.IsExistsUserQuestionBookmarkByQuestinIdUserId(questionId,User.GetUserId()))
            {
                ViewBag.bookmarks = true;
            }

            ViewData["tags"] = await _questionService.GetTagsByQuestionId(questionId);
            return View(question);
        }
        [Route("q/{questionId}")]
        public async Task<IActionResult> GetQuestionDetailsByShortLink(long questionId)
        {
            var question = await _questionService.GetQuestionById(questionId);
            if (question == null) return NotFound();

            return RedirectToAction("GetQuestionDetails", "Question", new { questionId = questionId });
        }


        [Route("AnswerQuestion")]
        [Authorize]
        public async Task<IActionResult> AnswerQuestion(AnswerQuestionViewModel answerQuestion)
        {
            if (string.IsNullOrEmpty(answerQuestion.Answer))
            {
                return new JsonResult(new { status = "empty" });
            }
            var userId = User.GetUserId();
            answerQuestion.UserId = userId;
            var result = await _questionService.AnswerQuestion(answerQuestion);
            if (result)
            {

SwitchSupport.Web/ViewComponents/QuestionAnswerListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SwitchSupport.Application.Services.Interfaces;

namespace SwitchSupport.Web.ViewComponents
{
    public class QuestionAnswerListViewComponent : ViewComponent
    {
        private readonly IQuestionService _questionService;
        public QuestionAnswerListViewComponent(IQuestionService questionService)
        {
            _questionService = questionService;
        }

        public async Task<IViewComponentResult> InvokeAsync(long questionId)
        {
            return View("QuestionAnswerList",await _questionService.GetQuestionAnswerList(questionId));
        }
    }
}

SwitchSupport.Web/Views/Question/CreateQuestion.cshtml
@using SwitchSupport.Domain.ViewModels.Question;
@model CreateQuestionViewModel
@{
    ViewData["Title"] = "ثبت پرسش جدید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles
    {
	<link rel="stylesheet" type="text/css" href="~/common/custom/ckeditor.css" />
    <link rel="stylesheet" type="text/css" href="/css/form.css">
    <link rel="stylesheet" type="text/css" href="/css/page.css">
    <link rel="stylesheet" type="text/css" href="/css/question.css">
    <link rel="stylesheet" type="text/css" href="/common/magicsuggest/magicsuggest.css">
    <link href="~/common/custom/autocomplete.css" rel="stylesheet" />
}

    @section Header
    {
    <partial name="_Header" />
}

    <div class="user-page-style">

        <div class="breadcumb-layer">
            <div class="container">
                <ul itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
                    <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="/" itemprop="item"><span itemprop="name"> صفحه اصلی </span></a></li>
                    <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a asp-action="CreateQuestion" asp-controller="Question" itemprop="item"><span itemprop="name"> @ViewData["Title"] </span></a></li>
                </ul>
            </div>
        </div>

        <div class="questions-layer page-style">

            <div class="container">

                <div class="right-col">

                    <section class="question-submit-layer">

                        <header class="top-heading"><h1> <a href="">ثبت پرسش جدید</a> </h1></header>

                        <div class="inner">
                          <partial name="_QuestionSearchBoxPartial" />

                            <div class="submit-layer">
                                <p class="p-style"> لطفا قبل از ثبت پرسش قوانین را مطالعه نمایید ، ثبت پرسش شما تایید قوانین محسوب خواهد شد :</p>
                                <ul>
                                    <li> ادب و احترام در گفتگو می بایست رعایت شود ، در صورت مشاهده تخلف کاربری شما مسدود خواهد شد. </li>
                                    <li> از ثبت پرسش تکراری خودداری نمایید. </li>
                                    <li> عنوان پرسش واضح و تا حد امکان کوتاه باشد. </li>
                                    <li> از تگ های کاملا مرتبط استفاده نمایید. </li>
                                    <li> جهت کسب پاسخ صریح ، متن پرسش خود را کاملا واضح ارسال نمایید. </li>
                                </ul>

                                <form class="form-layer-style" asp-action="CreateQuestion" asp-controller="Question">
                                    <input type="hidden" id="SelectTagsJson" name="SelectTagsJson" value="@Model?.SelectTagsJson"/>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="input-layer">
                                                <label asp-for="Title"></label>
                                                <input asp-for="Title" type="text">
                                                <span asp-validation-for="Title"></span>
                                            </div>
                                        </div>
                                        <div class="col-xs-12">
                                            <div class="textarea-layer">
                                                <label asp-for="Description"></label>
                                                <textarea asp-for="Description" class="editor"></textarea> 
                                                <span asp-validation-for="Description"></span>
                                            </div>
                                        </div>
                                        <div class="col-xs-12">
                                            <div class="input-layer">
                                                <!-- Use YourSelf autocomplete Plugin -->
                                                <label> <i class="icon-document"></i> تگ های مرتبط با پرسش شما </label>
                                                <input class="magicsuggest" id="SelectTags" asp-for= "SelectTags">
                                                <span asp-validation-for="SelectTags"></span>
                                            </div>
                                        </div>
                                        <div class="col-md-3 col-sm-4 col-xs-7 pull-left">
                                            <button class="submit-button green"> <span>ثبت پرسش</span> </button>
                                        </div>

                                    </div>
                                </form>
                            </div>
                        </div>
                    </section>

                </div>

                <partial name="_LeftSide" />

                <div class="clearfix"></div>

            </div>

        </div>

    </div>

    @section Scripts
    {
    <partial name="_JqueryValidation" />
	
    <script src="/js/question.js"></script>
    <script src="~/common/magicsuggest/magicsuggest.js"></script>
    <partial name="_Autocomplete" />
    <script>
        $(function(){
           var ms =  $("#SelectTags").magicSuggest({
                method: 'get',
                queryParam: 'name',
                data: 'get-tags',
                minChars: 2,
                placeholder: 'لطفا تگ های مورد نظر خود را وارد کنید',
                style: 'direction: ltr !important',
                minCharsRenderer: function (v) {
                    return 'لطفا حداقل 2 کاراکتر را وارد کنید';
                },
                noSuggestionText: '{{name}} وارد شده در پیشنهادات سایت موجود نیست',
            });
            var jsonval = $("#SelectTagsJson").val();
            if(jsonval !== '')
            {
                ms.setValue(JSON.parse(jsonval));
            }
        });   
    </script>

}

   

SwitchSupport.Web/Views/Question/EditAnswer.cshtml
@model SwitchSupport.Domain.ViewModels.Question.EditAnswerViewModel

@{
    ViewData["Title"] = "ویرایش پاسخ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles
    {
    <link rel="stylesheet" type="text/css" href="/css/form.css">
    <link rel="stylesheet" type="text/css" href="/css/page.css">
    <link rel="stylesheet" type="text/css" href="/css/question.css">
}

@section Header
    {
    <partial name="_Header" />
}

<div class="user-page-style">

    <div class="breadcumb-layer">
        <div class="container">
            <ul itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
                <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="/" itemprop="item"><span itemprop="name"> صفحه اصلی </span></a></li>
                <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="javascript:void(0)" itemprop="item"><span itemprop="name"> @ViewData["Title"] </span></a></li>
            </ul>
        </div>
    </div>

    <div class="questions-layer page-style">

        <div class="container">

            <div class="right-col">

                <section class="question-submit-layer">

                    <header class="top-heading"><h1> <a href="javascript:void(0)">@ViewData["Title"]</a> </h1></header>

                    <div class="inner">

                        <div class="submit-layer">

                            <form class="form-layer-style" asp-action="EditAnswer" asp-controller="Question">
                                <div class="row">

                                    <input type="hidden" asp-for="AnswerId" />
                                    <input type="hidden" asp-for="QuestionId" />

                                    <div class="col-xs-12">
                                        <div class="textarea-layer">
                                            <label asp-for="Answer" class="mb-10"></label>
                                            <textarea class="editor" asp-for="Answer"></textarea>
                                            <span asp-validation-for="Answer"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-3 col-sm-4 col-xs-7 pull-left">
                                        <button type="submit" class="submit-button green"> <span>ویرایش پاسخ</span> </button>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </section>

            </div>

            <partial name="_LeftSide" />

            <div class="clearfix"></div>

        </div>

    </div>

</div>

@section Scripts
    {
    <partial name="_JqueryValidation" />
    <script src="/js/question.js"></script>
}

SwitchSupport.Web/Views/Question/FilterTag.cshtml
@using SwitchSupport.Domain.ViewModels.Question
@model SwitchSupport.Domain.ViewModels.Question.FilterTagViewModel

@{
    ViewData["Title"] = "لیست تگ ها";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles
{
<link rel="stylesheet" type="text/css" href="/css/page.css">
<link rel="stylesheet" type="text/css" href="/css/tags.css">
}

@section Header
{
<partial name="_Header" />
}

<div class="user-page-style">

    <div class="breadcumb-layer">
        <div class="container">
            <ul itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
                <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="/" itemprop="item"><span itemprop="name"> صفحه اصلی </span></a></li>
                <li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="javascript:void(0)" itemprop="item"><span itemprop="name"> @ViewData["Title"] </span></a></li>
            </ul>
        </div>
    </div>

    <div class="tags-page page-style">

        <div class="container">

            <div class="right-col">
                <header class="top-heading">
                    <h1><a href="javascript:void(0)"> @ViewData["Title"] </a></h1>
                    <span> <i>@Model.AllCountEntities</i> تگ  </span>
                </header>
                <!-- Top -->
                <form asp-action="FilterTag" method="get" id="filter_form">
                    <input type="hidden" asp-for="CurrentPage" />
                    <div class="top-layer">
                        <div class="search-layer">
                            <input type="text" asp-for="Title" placeholder="دنبال چه تگی میگردی ؟ ">
                            <button type="submit"><i class="icon-search"></i></button>
                        </div>
                        <div class="filter-layer">
                            <div class="select-layer">
                                <select asp-for="Sort" onchange="SubmitTagForm()" asp-items="Html.GetEnumSelectList(typeof(FilterTagSortEnum))"></select>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /Top -->
                <!-- tags layer -->
                <div class="tags-list-layer">
                    <div class="row">
                        @if (Model.Entities.Any())
                        {
                            foreach (var tag in Model.Entities)
                            {
                                <!-- col -->
                                <div class="col-md-4 col-sm-6 col-xs-6 tag-col">
                                    <article>
                                        <h2><a asp-action="QuestionListBtTag" asp-route-tagName="@tag.Title"> @tag.Title </a></h2>
                                        @if (!string.IsNullOrEmpty(tag.Description))
                                        {
                                            <p> @tag.Description </p>
                                        }
                                        else
                                        {
                                            <p> توضیحات ثبت نشده است </p>
                                        }
                                        <div class="detail">
                                            <span> <i>@tag.UseCount</i> پرسش </span>
                                        </div>
                                    </article>
                                </div>
                                <!-- /col -->
                            }
                        }
                    </div>
                </div>
                <!-- /tags layer -->

                <partial name="_SitePaging" model="Model.GetPaging()" />

            </div>

            <partial name="_LeftSide" />

            <div class="clearfix"></div>

        </div>

    </div>

</div>  

SwitchSupport.Web/Views/Question/GetQuestionDetails.cshtml
@using SwitchSupport.Application.Extensions
@using SwitchSupport.Application.Statics
@model SwitchSupport.Domain.Entities.Questions.Question
@using SwitchSupport.Domain.ViewModels.Question

@{
	ViewData["Title"] = "جزئیات سوال";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var tags = ViewData["tags"] as List<string>;
}

@section Styles
	{
	<link rel="stylesheet" type="text/css" href="/css/page.css">
	<link rel="stylesheet" type="text/css" href="/css/question.css">
}

@section Header
	{
	<partial name="_Header" />
}

<div class="user-page-style">

	<div class="breadcumb-layer">
		<div class="container">
			<ul itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
				<li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="/" itemprop="item"><span itemprop="name">صفحه اصلی</span></a></li>
				<li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a asp-action="QuestionList" asp-controller="Question" itemprop="item"><span itemprop="name"> پرسش ها </span></a></li>
				<li itemtype="http://schema.org/ListItem" itemscope itemprop="itemListElement"><a href="javascript:void(0)" itemprop="item"><span itemprop="name"> @Model.Title </span></a></li>
			</ul>
		</div>
	</div>

	<div class="questions-layer page-style">

		<div class="container">

			<div class="right-col">

				<!-- question content -->
				<section class="question-content-layer">

					<header>
						<!-- use this button for edit Post , show only for author -->
						<button onclick="LoadUrl('@Url.Action("EditQuestion","Question",new {questionId = Model.Id})')"><i class="icon-pencil-edit"></i></button>

						<h1><a href="javascript:void(0)"> @Model.Title </a></h1>
						<span> @Model.CreateDate.TimeAgo() </span>
						<span><i> @Model.ViewCount </i> بازدید </span>
						<span><i> @Model.Answers.Count(s => !s.IsDelete) </i> پاسخ </span>
						<span><i> @Model.Score </i> امتیاز </span>
					</header>
					@Html.AntiForgeryToken();
					<article id="questindetails">
						<div class="inner">

							@Html.Raw(Model.Content)

							<div class="rating-layer">
								<div class="scoring-layer">
									<button onclick="ScoreUpForQuestion(@Model.Id)" class="plus"><i class="icon-caret-up"></i></button>
									<span> @Model.Score </span>
									<button onclick="ScoreDownForQuestion(@Model.Id)" class="negative"><i class="icon-caret-down"></i></button>
								</div>
								<div class="star-rating">
									<button onclick="AddQuestionToBookmark('@Model.Id')" class="@((ViewBag.bookmarks) ? "gold-color" : string.Empty)"><i class="icon-star"></i></button>
								</div>
							</div>

						</div>

						<div class="detail-layer">
							<div class="author">
								<a href="javascript:void(0)" class="img-layer">
									<img src="@(PathTools.UserAvatarPath + Model.User.Avatar)">
								</a>
								<h3><a href="javascript:void(0)"> @Model.User.GetUserDisplayName() </a></h3>
							</div>
							<a href="javascript:void(0)"> <i class="icon-back-arrow"></i> ثبت پاسخ به این پرسش </a>
							<div class="share-layer">
								<span> به اشتراک گذاری </span>
								<div class="share-detail">
									<div class="short-link">
										<p> لینک کوتاه شامل شناسه شما </p>
										<input type="text" name="" readonly value="@($"{PathTools.SiteAddress}/q/{Model.Id}")">
									</div>
									<div class="socials">
										@*<a href=""><i class="icon-facebook"></i></a>*@
										<a href="https://telegram.me/share/url?url=@($"{Context.Request.Scheme}://{Context.Request.Host + Context.Request.Path}")"><i class="icon-telegram"></i></a>
									</div>
								</div>
							</div>
						</div>
					</article>

					<!-- tags -->
					<div class="post-tags-layer">
						<div class="tags-layer">
							@foreach (var item in tags)
							{
								<a asp-action="QuestionListByTag" asp-controller="Question" asp-route-tagName=" @item"> @item </a>
							}

						</div>
					</div>
					<!-- /tags -->
					<!-- answer -->
					<div class="answers-layer" id="AnswersBox">
						<div class="top-layer">
							<h4><span> @Model.Answers.Count(s => !s.IsDelete) </span> پاسخ به این پرسش </h4>
						</div>

						@await Component.InvokeAsync("QuestionAnswerList", new { questionId = Model.Id })

					</div>
					@if (User.Identity.IsAuthenticated)
					{
						<partial name="_AnswerFormPartial" model="new AnswerQuestionViewModel { QuestionId = Model.Id }" />
					}
					else
					{
						<div class="alert alert-info">
							برای پاسخ به سوال ابتدا باید وارد حساب کاربری خود شوید .
						</div>
					}
				</section>
				<!-- /question content -->

			</div>

			<partial name="_LeftSide" />

		</div>

	</div>
	
</div>

@section Scripts
	{
	<partial name="_JqueryValidation" />
	<script src="/js/question.js"></script>

}